### ISSUE TITLE
[FEATURE] What Is the Time Line for Adding RHEL Support?

### ISSUE THREAD

**Issue by TheCedarPrince** [r-lib/rig#130] opened 2022-11-13 03:41 UTC
Hi @r-lib Team! 

This looks like a very very great solution for managing multiple versions of R on the same machine -- amazing! I was wondering, when might support for RHEL-based operating systems (e.g. Fedora, RHEL, etc.) be added to this tool? I would be more than happy to help with beta testing support if that could help move the needle along with adding support for RHEL-based OS's. 

Thanks! 

~ tcp :deciduous_tree:

**Comment by gaborcsardi** [comment] 2022-11-13 08:24
We can only add support for distributions we have R builds for: https://github.com/rstudio/r-builds/#supported-platforms

**Comment by gaborcsardi** [comment] 2022-11-13 08:24
Otherwise this is a duplicate of #28.

**Closed by gaborcsardi** 2022-11-13 08:24 UTC

**Comment by gaborcsardi** [comment] 2022-11-14 15:11
I don't know.

**Comment by TheCedarPrince** [comment] 2023-09-04 04:18
Thanks for adding support for RHEL-based distros! Just put `rig` on my newest machine running Fedora and it is brilliant!
