### ISSUE TITLE
RIG is not set in the run directory

### ISSUE THREAD

**Issue by acastillom24** [r-lib/rig#139] opened 2023-01-22 18:03 UTC
A few weeks ago when running rig, the working directory was set to the run directory, now rstudio starts in the home directory.

rstudio version:
![image](https://user-images.githubusercontent.com/81824205/213932276-dd6c5cae-85a6-44fd-b91e-f7abd10298a3.png)

**Comment by gaborcsardi** [comment] 2023-01-22 19:52
I am not entirely sure what you mean. Maybe this is a duplicate of #134?

**Comment by acastillom24** [comment] 2023-01-23 03:00
Hi gaborcsardi,
![image](https://user-images.githubusercontent.com/81824205/213958593-3e9f8152-2b62-4f3f-a882-d59706b3ce91.png)
I am working in the directory {D:\Proyectos\GIT\R}, rstudio was previously started with this same directory. But now it starts in the home directory.
![image](https://user-images.githubusercontent.com/81824205/213958960-d4dce9a0-ab2b-47ba-959b-4e8d53ae4d17.png)

**Comment by gaborcsardi** [comment] 2023-02-18 16:47
Bye "previously" previously, do you mean a previous version of rig, or a previous version of RStudio? I suspect the latter.

**Comment by acastillom24** [comment] 2023-02-19 22:11
thanks, I just reinstalled version 2022.07 - Spotted Wakerobin and it works correctly. On the other hand, one of the interesting things about using version 2022.12 is: Highlight R function calls.

**Closed** 2023-08-27 22:11 UTC
Labels: bug

**Comment by gaborcsardi** [comment] 2023-08-28 07:08
I fixed this on Windows, but so far could not find a way to set the working directory on macOS and Linux.

**Comment by gaborcsardi** [comment] 2023-08-28 09:03
OK, now works on all OSes, with newer RStudio versions (>= 2023.06.0).
